# Generated by Django 4.2.5 on 2023-09-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
