# Generated by Django 4.2.5 on 2023-09-26 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_product_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='qty',
            new_name='price',
        ),
    ]
